---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/en
  label: Pages in english
  create: documents
  match: "**/*"
  new_doc_ext: ".md"
  templates:
  - pages-in-spanish
- type: directory
  path: content/es
  label: Pages in spanish
  create: documents
  match: "**/*"
  new_doc_ext: ".md"
  templates:
  - pages-in-spanish
upload_dir: public/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
